
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/db_locadora?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

